Repository tryber/sd-010-b-project-trivia-react-redux, pull requests merged in 2021-06, with the labels that each got.

#8 [GRUPO 8] [Projeto Trivia] 💯 🚀
  src/App.js
  src/pages/Login.js
Labels: code-review

#14 [GRUPO 3]Project-trivia-react-redux
  package-lock.json
  package.json
  src/App.js
Labels: code-review

#2 [Group 05] Requisito 01
  src/App.js
  src/actions/index.js
  src/actions/types.js
  src/index.js
  src/pages/Login.jsx
  src/reducers/game.js
  src/reducers/index.js
  src/reducers/time.js
  src/reducers/user.js
  src/store/index.js
Labels: development

#22 first requirement is done
  src/App.js
  src/index.js
  src/pages/home.js
  src/reducer/index.js
  src/reducer/user.js
  src/store/index.js
Labels: code-review

#20 Atualizando req 01
  src/pages/Login.js
Labels: code-review

#25 Requisito 01 - Tela de login
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/Login.jsx
  src/reducers/index.js
  src/reducers/player.js
  src/store/index.js
Labels: code-review

#6 [PROJETO TRIVIA] [GRUPO 13]
  package-lock.json
  package.json
  src/App.js
  src/Home.js
  src/components/Header.js
  src/components/Questions.js
  src/index.js
  src/pages/Jogo.js
  src/pages/Login.js
  src/pages/Settings.js
  src/services/token.js
Labels: code-review

#31 feature 01
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/Login.jsx
  src/reducers/index.js
  src/store/index.js
Labels: code-review

#4 Main group 32 req 1
  package-lock.json
  package.json
  src/App.js
  src/Pages/Login.jsx
  src/actions/index.js
  src/index.js
  src/reducers/index.js
  src/reducers/loginReducer.js
  src/services/fetchToken.js
  src/store/index.js
Labels: code-review

#43 Main group 3 req 1.1
  src/App.js
  src/pages/Login.jsx
Labels: code-review

#27 [Requisito 1] [Code Review] [Done]
  package-lock.json
  package.json
  src/App.js
  src/components/Header.jsx
  src/index.js
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/pages/Ranking.jsx
  src/redux/reducers/index.jsx
  src/redux/reducers/loginReducer.jsx
  src/redux/store/index.jsx
Labels: code-review

#1 [Grupo 9] [Projeto Trivia React Redux]
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/API
  src/components/Form.js
  src/index.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/Login.js
  src/pages/Ranking.js
  src/reducers/apiReducer.js
  src/reducers/index.js
  src/reducers/playerReducer.js
  src/store/index.js
Labels: code-review

#40 [GRUPO 26] Requisito 1 completo
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/components/Login.js
  src/index.js
  src/reducers/index.js
  src/reducers/login.js
  src/store/index.js
Labels: code-review

#42 G8 req04
  package-lock.json
  package.json
  src/components/Header.jsx
  src/pages/Login.js
Labels: code-review

#61 Main group 32 req 2
  src/App.js
  src/Pages/Game.jsx
  src/Pages/Login.jsx
  src/reducers/index.js
  src/services/fetchToken.js
Labels: code-review

#58 feature 03
  src/App.js
  src/pages/Config.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
Labels: code-review

#16 Main-group-7 Requisito1
  package-lock.json
  package.json
  src/App.js
  src/pages/Login.js
Labels: code-review

#56 [GRUPO 9][REQUISITO 2]
  src/App.js
  src/actions/Game
  src/components/Form.js
Labels: code-review

#74 [ GROUP 4] Main group 4 requisito 2
  src/pages/Login.jsx
Labels: code-review

#73 [main-group-17-req-2]
  README.md
  package-lock.json
  src/App.js
  src/actions/index.js
  src/actions/userAction.js
  src/pages/Game.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/user.js
  src/services/triviaApi.js
Labels: code-review

#70 [Grupo 8] - Requisito 03
  src/App.js
  src/components/Home.js
  src/index.js
  src/pages/Configs.js
  src/pages/Login.js
Labels: code-review

#71 [Requisito 3] {Code Review] [Done]
  src/App.js
  src/pages/Config.jsx
  src/pages/Login.jsx
  src/redux/reducers/loginReducer.jsx
Labels: code-review

#29 [Group 10] [Req 01]
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/triviaGame.js
  src/store/index.js
Labels: development

#69 Inicializando req 05
  src/App.js
  src/Services/api.js
  src/pages/Game.js
  src/pages/Login.js
Labels: code-review

#82 Group-19-req-04
  src/App.js
  src/actions/index.js
  src/components/Header.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/reducers/player.js
Labels: code-review

#86 Requisitos ate o 5 completos e atualizados v2.0
  src/App.js
  src/components/Home.js
  src/pages/Login.js
Labels: code-review

#52 requisito 1 e pastas do redux
  src/App.js
  src/App.test.js
  src/actions/index.js
  src/index.js
  src/pages/Login.js
  src/reducers/index.js
  src/store/index.js
Labels: development

#87 [Group 10] [Req 3]
  src/App.js
  src/pages/Login.js
  src/pages/Settings.js
Labels: development

#106 Main group 30 correcao lint
  package-lock.json
  src/index.js
  src/pages/Login.jsx
  src/reducers/apiReducer.jsx
  src/reducers/userReducer.jsx
  src/services/index.js
  src/store/index.jsx
Labels: code-review

#104 Main group 20 req 04
  README.md
  package-lock.json
  src/App.js
  src/components/Header.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/userReducer.js
  src/redux/store/index.js
  src/services/api/getAvatar.js
Labels: code-review

#114 [Main-group-20][Req-2]
  package-lock.json
  package.json
  src/pages/Login.jsx
Labels: code-review

#103 Main-group-7 Requisito 12 - Montagem inicial do Redux
  package-lock.json
  package.json
  src/App.js
  src/Redux/action/index.js
  src/Redux/action/setUserAction.js
  src/Redux/reducers/index.js
  src/Redux/reducers/user.js
  src/Redux/store/index.js
  src/components/Header.js
  src/index.js
  src/pages/Config.js
  src/pages/Feedback.js
  src/pages/GamePlayer.js
  src/pages/Login.js
  src/pages/Ranking.js
Labels: code-review

#63 Main group 27 - DONE REQ 1, 2 AND 3
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/components/Login.js
  src/index.js
  src/pages/Home.js
  src/pages/Settings.js
  src/pages/TriviaGame.js
  src/reducers/index.js
  src/reducers/trivia.js
  src/reducers/user.js
  src/services/trivia.js
  src/store/index.js
Labels: code-review

#117 Bug: Resolvendo problema no package-lock.json
  package-lock.json
Labels: code-review

#118 Grupo 29 -req 4 - em andamento
  src/components/Header.js
  src/components/Login.jsx
  src/pages/Game.jsx
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/user.js
Labels: code-review

#116 Grupo 22 requisito 3
  src/App.js
  src/pages/Login.jsx
  src/pages/Settings.jsx
Labels: code-review

#79 req 2 tentativa 1, imple.combine
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/reducers/index.js
  src/reducers/loginReducer.js
  src/services/index.js
  src/store/index.js
Labels: code-review

#135 [Group 23][Req 1 Redux]
  package-lock.json
  package.json
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/playerReducer.js
  src/redux/store/index.js
Labels: code-review

#134 Main group 34 req7
  package-lock.json
  src/App.js
  src/actions/index.js
  src/components/GameHeader.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/pages/Settings.jsx
  src/reducers/game.js
  src/reducers/index.js
Labels: code-review

#131 Requisito 2 feito com sucesso.
  package-lock.json
  package.json
  src/components/Inputs.jsx
  src/redux/actions/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/reducer.js
  src/redux/store/index.js
Labels: code-review

#66 [GRUPO 9][REQUISITO 3]
  src/App.js
  src/components/Setting.js
  src/pages/Login.js
  src/pages/Settings.js
Labels: code-review

#143 Main group 20 [Erros de nomenclatura]
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/loginReducer.jsx
  src/services/api/getTriviaQuestions.js
Labels: code-review

#91 [Grupo 15] Req 2 - creates a TriviaGame page and save user token on local storage
  src/App.js
  src/action/index.js
  src/pages/Login.jsx
  src/pages/TriviaGame.jsx
  src/reducers/user.js
  src/services/API.js
Labels: code-review

#105 [GRUPO 9] [REQUISITO4]
  package-lock.json
  package.json
  src/actions/Game
  src/actions/gameAction.js
  src/components/Form.js
  src/components/SettingBtn.js
  src/pages/Game.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/playerReducer.js
  src/store/index.js
Labels: code-review

#119 Main group 27, done req 5, 6 and 7
  src/actions/index.js
  src/components/GameHeader.js
  src/components/Questions.js
  src/pages/TriviaGame.js
  src/reducers/index.js
  src/reducers/trivia.js
  src/reducers/user.js
  src/store/index.js
Labels: code-review

#156 Main group 31 - requisito 01 - cria tela login
  cypress/integration/project.spec.js
  src/App.js
  src/App.test.js
  src/actions/index.js
  src/components/LoginForm.jsx
  src/index.js
  src/pages/LoginPage.js
  src/reducers/index.js
  src/reducers/userLogin.js
  src/store/index.js
Labels: development

#111 adiciona o redux
  package-lock.json
  package.json
  src/actions/index.js
  src/index.js
  src/reducers/index.js
  src/reducers/playerReducer.js
  src/store/index.js
Labels: code-review

#165 Main-group-7 requisito 3
  src/pages/Config.js
  src/pages/Login.js
Labels: code-review

#154 Main group 34 req10
  src/pages/Game.jsx
  src/pages/style.css
Labels: code-review

#149 [MAIN-GROUP-3][REQ 4]
  src/actions/index.js
  src/components/Hash.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/reducers/loginReducer.js
Labels: code-review

#187 [GRUPO 33] Req-00
  package-lock.json
  package.json
  src/App.js
  src/components/Header.js
  src/components/pages/Login.js
  src/redux/actions/player.js
  src/redux/reducers/index.js
  src/redux/reducers/player.js
  src/redux/store/index.js
Labels: code-review

#196 [ Group 4 ] Requisito 4
  package-lock.json
  package.json
  src/actions/index.js
  src/components/Header.jsx
  src/index.css
  src/index.js
  src/pages/GamePage.jsx
  src/pages/Login.jsx
  src/reducers/user.jsx
Labels: code-review

#189 Main Group 26 - Requisito 3
  src/App.js
  src/components/ButtonSettings.js
  src/components/Login.js
  src/pages/Settings.js
Labels: code-review

#198 [Group 23][Requirement 02]
  src/App.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/reducers/playerReducer.js
  src/services/api.js
Labels: code-review

#205 [Grupo 15] Req 5 - work in progress
  package-lock.json
  src/App.js
  src/action/index.js
  src/components/Header.jsx
  src/components/LoginForms.jsx
  src/pages/Login.jsx
  src/pages/Settings.jsx
  src/pages/TriviaGame.jsx
  src/pages/index.js
  src/reducers/index.js
  src/reducers/player.js
  src/reducers/user.js
Labels: bug, development

#201 [Main group 23] [Req 04]
  src/components/Header.jsx
Labels: code-review

#190 adiciona configuraçoes de redux no componente HEADER
  src/components/Header.jsx
  src/pages/Login.js
Labels: code-review

#162 Inicio req 07
  package-lock.json
  src/pages/Game.js
Labels: code-review

#212 [MAIN-GROUP-3][REQ 7]
  src/components/Questions.css
  src/components/Questions.jsx
Labels: code-review

#174 [Main group 20][Req-05][Andamento]
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/questReducer.js
  src/services/api/getTriviaQuestions.js
Labels: code-review

#219 Main-group-7 Tela de jogo
  src/pages/GamePlayer.js
Labels: code-review

#221 Main group 6 feature 05
  src/components/Header.jsx
  src/components/Question.jsx
  src/history.js
  src/index.js
  src/pages/Game.jsx
  src/pages/Login.jsx
Labels: code-review

#225 Grupo 08 - Requisito 08 Finalizado 🚀
  package-lock.json
  src/App.js
  src/pages/Game.js
Labels: code-review

#231 Main group 20 [Req 07] [Done]
  src/App.css
  src/App.js
  src/index.css
  src/index.js
  src/pages/Game.jsx
  src/style/Game.css
Labels: code-review

#230 [Grupo 15] - Req 5 and 6 - render questions and alternatives on trivia game page
  src/action/index.js
  src/components/LoginForms.jsx
  src/pages/TriviaGame.jsx
  src/reducers/player.js
Labels: code-review

#177 iniciando req 5
  src/actions/gameAction.js
  src/components/Answer.js
  src/components/Form.js
  src/components/Question.js
  src/pages/Game.js
  src/pages/Login.js
  src/reducers/apiReducer.js
Labels: code-review

#222 Main-group-7 requisito13
  package-lock.json
  src/Redux/action/actionAddAssertion.js
  src/Redux/action/index.js
  src/Redux/reducers/user.js
  src/components/Header.js
  src/pages/Feedback.js
  src/pages/GamePlayer.js
Labels: code-review

#184 Main group 34 req9
  src/actions/index.js
  src/pages/Game.jsx
  src/pages/GameHeader.jsx
  src/reducers/player.js
Labels: code-review

#262 [main-group-26-requisito-8]
  src/components/Game.js
  src/components/Timer.js
  src/reducers/index.js
  src/reducers/timeout.js
Labels: code-review

#280 Main-group-7 Mais ajustes botoes Mariana
  src/pages/GamePlayer.js
Labels: code-review

#283 [Group 23][Requirements 05 - 06 - 07. New]
  package-lock.json
  src/App.css
  src/components/TriviaGame.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/services/api.js
Labels: code-review

#287 Main group 31 - requisito 2 - start button
  src/App.js
  src/actions/index.js
  src/components/LoginForm.jsx
  src/reducers/index.js
  src/reducers/token.js
Labels: code-review

#270 Requisito 5(versao2)
  package-lock.json
  src/components/Inputs.jsx
  src/pages/Game.jsx
  src/redux/action/index.js
  src/redux/actions/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/reducer.js
Labels: code-review

#294 [Main group 23] [req 04][Change made]
  src/components/TriviaGame.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
Labels: code-review

#301 [GRUPO 19] Main group 19 req 09
  src/actions/index.js
  src/components/Header.js
  src/components/Questions.js
  src/reducers/player.js
Labels: code-review

#263 [Grupo 15] Req 7 - change the border color of the answers when the questions are answered
  src/App.css
  src/pages/TriviaGame.jsx
Labels: code-review

#303 [Group 10] [Req 7]
  src/components/Answers.js
  src/components/answersColors.css
  src/pages/GamePage.js
  src/pages/GamePlay.js
Labels: code-review

#305 Main-group-7 requisito14, 15, 16 e correções
  src/Redux/action/index.js
  src/Redux/action/reloadAction.js
  src/Redux/reducers/user.js
  src/pages/Feedback.js
  src/pages/GamePlayer.js
  src/pages/Login.js
  src/pages/Ranking.js
Labels: code-review

#313 Grupo 22 - Requisito 5
  src/components/Inputs.jsx
  src/pages/Game.jsx
  src/redux/actions/index.js
Labels: code-review

#324 Req 11 - redirects to the feedback page when the last questions are answered
  src/App.js
  src/components/Timer.jsx
  src/pages/Feedback.jsx
  src/pages/Login.jsx
  src/pages/TriviaGame.jsx
  src/pages/index.js
Labels: code-review

#309 [Main-group-20][Req-08]
  src/components/Cronometer.jsx
  src/pages/Game.jsx
Labels: code-review

#292 G08 req9
  src/components/Header.jsx
  src/pages/Game.js
Labels: code-review

#326 [GRUPO 33] Req-02
  package-lock.json
  src/App.js
  src/components/Header.jsx
  src/functions/index.js
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/actions/player.js
  src/redux/reducers/player.js
  src/services/api.js
Labels: code-review

#243 main-group-26-requisito-5
  src/actions/index.js
  src/components/Game.js
  src/components/Login.js
  src/components/Quiz.js
  src/reducers/index.js
  src/reducers/quiz.js
  src/reducers/timeout.js
  src/services/APIQuiz.js
Labels: code-review

#325 [GRUPO 19] Main group 19 MIN =D
  src/App.js
  src/pages/Feedback.jsx
  src/pages/Ranking.jsx
Labels: code-review

#344 main-group-26-requisito-7
  src/App.css
  src/components/Quiz.js
Labels: code-review

#329 [Group 9][Requisito 7]
  src/components/Answer.js
Labels: code-review

#317 [GROUP 33] Req 04
  src/components/Header.jsx
  src/functions/index.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/actions/player.js
  src/redux/reducers/player.js
  src/services/api.js
Labels: code-review

#352 [Main-group-20] req 10
  src/pages/Game.jsx
Labels: code-review

#362 Main group 32 req 8
  src/Components/Chronometre.jsx
  src/Pages/Game.jsx
  src/actions/index.js
  src/reducers/index.js
  src/reducers/timerReducer.js
Labels: code-review

#356 [Group 23][Req 10]
  src/App.css
  src/components/Header.jsx
  src/components/TriviaGame.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/pages/Settings.jsx
  src/services/api.js
Labels: code-review

#358 Main group 20 [Req 09] [Done]
  src/components/Cronometer.jsx
  src/components/Header.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducers/questReducer.js
  src/services/api/getTriviaQuestions.js
  src/services/helpers/getAvatar.js
  src/services/helpers/localStorage.js
Labels: code-review

#375 Grupo 22 - Requisito 7
  src/App.css
  src/pages/Game.jsx
Labels: code-review

#312 Group 31 Requisito 12/13
  src/App.js
  src/components/FeedBackHeader.jsx
  src/components/FeedBackMain.jsx
  src/pages/FeedBackPage.js
Labels: code-review

#284 G8 req11
  src/App.css
  src/App.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/Login.js
Labels: code-review

#395 Adiciona o botão de próxima pergunta (requisito 10)
  src/Components/Chronometre.jsx
  src/Pages/Game.jsx
Labels: code-review

#357 iniciando correções do requisito 8
  src/components/Quiz.js
  src/components/Timer.js
  src/reducers/timeout.js
Labels: code-review

#399 [Group 4] Requisito 5-Feito no dia 17 pela manhã!
  src/components/ButtonSettings.jsx
  src/components/Header.jsx
  src/pages/GamePage.jsx
  src/pages/Login.jsx
  src/services/API.js
Labels: code-review

#385 [Group 23][State fix]
  src/components/Timer.jsx
  src/components/TriviaGame.jsx
  src/redux/actions/index.js
  src/redux/reducers/gameReducer.js
  src/redux/reducers/playerReducer.js
  src/redux/store/index.js
Labels: code-review

#414 [GRUPO 33] Req 05
  src/functions/index.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/actions/game.js
  src/redux/actions/player.js
  src/redux/reducers/game.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  src/services/api.js
Labels: code-review

#420 G8 correcao de bugs
  src/pages/Feedback.js
  src/pages/Game.js
Labels: code-review

#415 Inicio do requisito 15
  src/pages/Feedback.js
  src/pages/Game.js
Labels: code-review

#377 [GROUP 33] req 12
  src/App.js
  src/components/Header.jsx
  src/pages/Config.jsx
  src/pages/Feedback.jsx
  src/pages/Login.jsx
  src/pages/Ranking.jsx
Labels: code-review

#405 Main group 26 requisito 13
  cypress/integration/project.spec.js
  src/App.js
  src/components/MsgFeedback.js
  src/pages/Feedback.js
Labels: code-review

#425 Main group 20 req 11
  src/App.js
  src/components/Cronometer.jsx
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/redux/actions/index.js
  src/redux/reducers/questReducer.js
Labels: code-review

#434 requisito 18 completo
  cypress/integration/project.spec.js
  src/components/Header.jsx
  src/pages/Ranking.js
Labels: code-review

#404 main-group-26-req11
  src/components/MsgFeedback.js
  src/components/Quiz.js
Labels: code-review

#433 [GROUP 33] req 18
  src/pages/Ranking.jsx
Labels: code-review

#432 [Main-Group-20][Req-18]
  src/pages/Ranking.jsx
Labels: code-review

#438 G8 correcao
  cypress/integration/project.spec.js
  src/components/Header.jsx
Labels: code-review

#181 Main group 20 req12 req13 req14
  src/components/FeedbackMessage.jsx
  src/components/Header.jsx
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/redux/actions/index.js
  src/redux/reducers/questReducer.js
Labels: development

#442 concluido req 16
  src/App.js
  src/pages/FeedBack.jsx
  src/pages/Ranking.jsx
Labels: code-review

#419 [Group 4] Main group 4 req 7
  src/GamePageCss.css
  src/pages/GamePage.jsx
Labels: code-review

#445 [Main group 20] [req 15]
  src/components/ButtonFeed.jsx
  src/pages/Feedback.jsx
Labels: code-review

#446 Main group 3 req 18
  src/pages/Ranking.jsx
Labels: code-review

#448 Main group 32 req 9
  src/App.js
  src/App.test.js
  src/Components/Header.jsx
  src/Pages/Feedback.jsx
  src/Pages/Game.jsx
  src/Pages/Login.jsx
Labels: code-review

#447 [Main group 23] [Req 09 fix marge]
  src/components/TriviaGame.jsx
  src/pages/Login.jsx
Labels: code-review

#452 Main group 6 - feature 07
  src/components/Question.jsx
  src/components/styleQuestion.css
Labels: code-review

#455 [Main group 11] [Tela de Feedback]
  src/App.js
  src/components/FeedbackMessages.js
  src/components/HeaderComponent.js
  src/pages/FeedbackPage.js
  src/pages/Login.js
  src/pages/RankingPage.js
Labels: code-review

#458 [Group 10] [Req 11]
  src/components/Answers.js
  src/pages/GamePlay.js
  src/reducers/triviaGame.js
Labels: code-review

#453 [GRUPO 33] Req07
  src/components/Timer.jsx
  src/pages/Game.jsx
  src/pages/css/Game.css
Labels: code-review

#451 Main group 20 req14
  src/components/FeedbackMessage.jsx
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/redux/actions/index.js
  src/redux/reducers/questReducer.js
Labels: code-review

#444 Main group 20 req13
  src/components/FeedbackMessage.jsx
  src/pages/Feedback.jsx
Labels: code-review

#400 [Group 9] [requisito9]
  src/actions/correctAnswer.js
  src/actions/gameAction.js
  src/components/API
  src/components/Answer.js
  src/components/Timer.js
  src/pages/Game.js
  src/reducers/gameReduce.js
  src/reducers/index.js
  src/reducers/playerReducer.js
Labels: code-review

#351 [Group 9] [Requisito 8]
  src/actions/gameAction.js
  src/components/Answer.js
  src/components/Timer.js
  src/pages/Game.js
  src/reducers/gameReduce.js
  src/reducers/index.js
Labels: code-review

#472 Main group 20 fix score
  src/components/FeedbackMessage.jsx
  src/components/Header.jsx
  src/pages/Game.jsx
  src/redux/reducers/questReducer.js
Labels: code-review

#469 [Group 23] [Req-11]
  src/App.js
  src/components/TriviaGame.jsx
  src/pages/Feedback.jsx
Labels: code-review

#271 [Main group 23] [Req 12]
  src/App.js
  src/components/HeaderFeedback.jsx
Labels: code-review

#388 Main group 15 req 15
  src/App.js
  src/action/index.js
  src/components/Header.jsx
  src/components/LoginForms.jsx
  src/components/Timer.jsx
  src/pages/FeedBack.jsx
  src/pages/Feedback.jsx
  src/pages/Ranking.jsx
  src/pages/TriviaGame.jsx
  src/pages/index.js
  src/reducers/player.js
Labels: code-review

#460 main-group-26-requisito-15
  cypress/integration/project.spec.js
  src/App.js
  src/components/ButtonSettings.js
  src/components/MsgFeedback.js
  src/components/Ranking.js
Labels: code-review

#473 main-group-26-requisito 9
  src/components/Header.js
  src/components/Quiz.js
  src/reducers/quiz.js
  src/reducers/timeout.js
Labels: code-review

#493 [Group 23][Req 12]
  src/components/Header.jsx
  src/components/HeaderFeedback.jsx
  src/pages/Feedback.jsx
Labels: code-review

#494 Grupo 22 - Requisito 14
  cypress/integration/project.spec.js
  src/functions/classNameFunction.js
  src/functions/combineArray.js
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
Labels: code-review

#500 Grupo 22 - Requisito 16 e 18
  cypress/integration/project.spec.js
  src/App.js
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/pages/Ranking.jsx
Labels: code-review

#497 [Group 4] Requisito 7 Completo
  src/App.css
  src/App.js
  src/components/ButtonFeedback.jsx
  src/components/ButtonLogin.jsx
  src/pages/Feedback.jsx
  src/pages/GamePage.jsx
Labels: code-review

#504 [Group 4] Main group 4 req 7 carlos vieira
  src/App.css
  src/GamePageCss.css
  src/pages/GamePage.jsx
Labels: code-review

#508 Main group 31 - gamepage req 5 e 6
  src/actions/index.js
  src/components/GameTrivia.jsx
  src/components/LoginForm.jsx
  src/pages/GamePage.js
  src/reducers/getQuestions.js
  src/reducers/index.js
  src/reducers/token.js
Labels: development

#318 [Main group 23] [Req 15]
  src/pages/Feedback.jsx
Labels: code-review

#499 [GRUPO 33] Req-08
  src/components/Timer.jsx
  src/pages/Game.jsx
  src/redux/actions/game.js
  src/redux/reducers/game.js
  src/redux/reducers/player.js
Labels: code-review

#511 Requisito 13 finalizado
  src/components/MsgFeedback.js
Labels: code-review

#509 Main group 4 req 7 carlos vieira
  src/GamePageCss.css
Labels: code-review

#475 salvando no storage ranking
  src/components/Questions.jsx
  src/pages/FeedBack.jsx
  src/pages/Login.jsx
  src/pages/Ranking.jsx
Labels: code-review

#512 [Group 23][Req 15]
  src/components/TriviaGame.jsx
  src/pages/Feedback.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducers/gameReducer.js
Labels: code-review

#522 Main group 31 - gamepage button styles req 7
  src/App.css
  src/components/GameTrivia.jsx
Labels: development

#328 [Main group 23] [Req 16]
  src/App.js
  src/pages/Feedback.jsx
  src/pages/Ranking.jsx
Labels: code-review

#523 [Group 23][Req 16]
  src/App.js
  src/pages/Feedback.jsx
  src/pages/Ranking.jsx
Labels: code-review

#533 Fim do requisito 14
  cypress/integration/project.spec.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/Ranking.js
Labels: code-review

#527 [GROUP 33] Req 10
  src/pages/Game.jsx
Labels: code-review

#492 [GRUPO 9][REQUISITO 16]
  src/components/Timer.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/Ranking.js
  src/reducers/playerReducer.js
Labels: code-review

#482 [GRUPO 9][REQUISITO 12]
  src/components/Answer.js
  src/components/Timer.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/reducers/playerReducer.js
Labels: code-review
